##################################################
resolver: lts-13.15

          # ^ ghc-8.6.4

#------------------------------------------------#

packages:

- ./mtg-types
- ./mtg-json
- ./mtg-csv/hs
- ./mtg-sql/hs

#------------------------------------------------#

extra-deps:

- ../spiros/spiros
- ../enumerate/enumerate

- conduit-find-0.1.0.3

##################################################